CREATE TABLE attendances
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id BIGINT                                  NOT NULL,
    date        date                                    NOT NULL,
    check_in    TIMESTAMP WITHOUT TIME ZONE,
    check_out   TIMESTAMP WITHOUT TIME ZONE,
    status      VARCHAR(255),
    work_type   VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_attendances PRIMARY KEY (id)
);

CREATE TABLE candidates
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    email        VARCHAR(255),
    phone_number VARCHAR(255),
    cv_url       VARCHAR(255),
    job_id       INTEGER                                 NOT NULL,
    status       VARCHAR(255),
    apply_date   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_candidates PRIMARY KEY (id)
);

CREATE TABLE departments
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    department_name   VARCHAR(255),
    location          VARCHAR(255),
    work_type         VARCHAR(255),
    employment_status VARCHAR(255),
    manager_id        BIGINT,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_departments PRIMARY KEY (id)
);

CREATE TABLE documents
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    url         VARCHAR(255),
    employee_id BIGINT,
    public_id   VARCHAR(255),
    uploaded_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_documents PRIMARY KEY (id)
);

CREATE TABLE employees
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id     VARCHAR(255),
    first_name      VARCHAR(255),
    last_name       VARCHAR(255),
    email           VARCHAR(255),
    mobile_number   VARCHAR(255),
    date_of_birth   date,
    gender          VARCHAR(255),
    nationality     VARCHAR(255),
    marital_status  VARCHAR(255),
    address         VARCHAR(255),
    city            VARCHAR(255),
    state           VARCHAR(255),
    zip_code        VARCHAR(255),
    slack_id        VARCHAR(255),
    github_id       VARCHAR(255),
    skype_id        VARCHAR(255),
    username        VARCHAR(255),
    designation     VARCHAR(255),
    employee_type   VARCHAR(255),
    joining_date    date,
    working_days    INTEGER,
    office_location VARCHAR(255),
    status          VARCHAR(255),
    department_id   BIGINT,
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE TABLE holiday
(
    holiday_id  INTEGER NOT NULL,
    name        VARCHAR(255),
    date        date,
    description VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_holiday PRIMARY KEY (holiday_id)
);

CREATE TABLE jobs
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_title       VARCHAR(255),
    job_description VARCHAR(255),
    department_id   BIGINT,
    location        VARCHAR(255),
    salary          DECIMAL,
    job_type        VARCHAR(255),
    status          VARCHAR(255),
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_jobs PRIMARY KEY (id)
);

CREATE TABLE leaves
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id BIGINT                                   NOT NULL,
    start_date  date                                     NOT NULL,
    end_date    date                                     NOT NULL,
    reason      VARCHAR(255)                             NOT NULL,
    status      VARCHAR(255)                             NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_leaves PRIMARY KEY (id)
);

CREATE TABLE notifications
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message     VARCHAR(255)                             NOT NULL,
    timestamp   TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    employee_id BIGINT                                   NOT NULL,
    is_read     BOOLEAN,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE TABLE payroll
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id      BIGINT                                  NOT NULL,
    ctc              DECIMAL(10, 2)                          NOT NULL,
    salary_per_month DECIMAL(10, 2)                          NOT NULL,
    deduction        DECIMAL(10, 2),
    status           VARCHAR(255)                            NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_payroll PRIMARY KEY (id)
);

CREATE TABLE projects
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                             NOT NULL,
    start_date  date                                     NOT NULL,
    end_date    date,
    status      VARCHAR(255)                             NOT NULL,
    employee_id BIGINT                                   NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email       VARCHAR(255),
    password    VARCHAR(255),
    full_name   VARCHAR(255),
    role        VARCHAR(255),
    otp         VARCHAR(255),
    is_verified BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE departments
    ADD CONSTRAINT uc_departments_departmentname UNIQUE (department_name);

ALTER TABLE departments
    ADD CONSTRAINT uc_departments_manager UNIQUE (manager_id);

ALTER TABLE employees
    ADD CONSTRAINT uc_employees_email UNIQUE (email);

ALTER TABLE employees
    ADD CONSTRAINT uc_employees_employeeid UNIQUE (employee_id);

ALTER TABLE jobs
    ADD CONSTRAINT uc_jobs_jobtitle UNIQUE (job_title);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE attendances
    ADD CONSTRAINT FK_ATTENDANCES_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE departments
    ADD CONSTRAINT FK_DEPARTMENTS_ON_MANAGER FOREIGN KEY (manager_id) REFERENCES employees (id);

ALTER TABLE documents
    ADD CONSTRAINT FK_DOCUMENTS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE employees
    ADD CONSTRAINT FK_EMPLOYEES_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (id);

ALTER TABLE jobs
    ADD CONSTRAINT FK_JOBS_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (id);

ALTER TABLE leaves
    ADD CONSTRAINT FK_LEAVES_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE notifications
    ADD CONSTRAINT FK_NOTIFICATIONS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE payroll
    ADD CONSTRAINT FK_PAYROLL_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE projects
    ADD CONSTRAINT FK_PROJECTS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);