CREATE TABLE password_reset_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(255),
    user_id     BIGINT                                  NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_passwordresettoken PRIMARY KEY (id)
);

ALTER TABLE payroll
    ADD bank_account VARCHAR(50);

ALTER TABLE payroll
    ADD bank_name VARCHAR(100);

ALTER TABLE users
    ADD otp_generated_time TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE password_reset_token
    ADD CONSTRAINT uc_passwordresettoken_user UNIQUE (user_id);

ALTER TABLE password_reset_token
    ADD CONSTRAINT FK_PASSWORDRESETTOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

DROP SEQUENCE attendances_id_seq CASCADE;

DROP SEQUENCE candidates_id_seq CASCADE;

DROP SEQUENCE departments_id_seq CASCADE;

DROP SEQUENCE documents_id_seq CASCADE;

DROP SEQUENCE employees_id_seq CASCADE;

DROP SEQUENCE jobs_id_seq CASCADE;

DROP SEQUENCE leaves_id_seq CASCADE;

DROP SEQUENCE notifications_id_seq CASCADE;

DROP SEQUENCE payroll_id_seq CASCADE;

DROP SEQUENCE projects_id_seq CASCADE;

DROP SEQUENCE users_id_seq CASCADE;

ALTER TABLE payroll
ALTER
COLUMN ctc TYPE DECIMAL(12, 2) USING (ctc::DECIMAL(12, 2));

ALTER TABLE payroll
ALTER
COLUMN deduction TYPE DECIMAL(12, 2) USING (deduction::DECIMAL(12, 2));

CREATE SEQUENCE IF NOT EXISTS attendances_id_seq;
ALTER TABLE attendances
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE attendances
    ALTER COLUMN id SET DEFAULT nextval('attendances_id_seq');

ALTER SEQUENCE attendances_id_seq OWNED BY attendances.id;

CREATE SEQUENCE IF NOT EXISTS candidates_id_seq;
ALTER TABLE candidates
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE candidates
    ALTER COLUMN id SET DEFAULT nextval('candidates_id_seq');

ALTER SEQUENCE candidates_id_seq OWNED BY candidates.id;

CREATE SEQUENCE IF NOT EXISTS departments_id_seq;
ALTER TABLE departments
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE departments
    ALTER COLUMN id SET DEFAULT nextval('departments_id_seq');

ALTER SEQUENCE departments_id_seq OWNED BY departments.id;

CREATE SEQUENCE IF NOT EXISTS documents_id_seq;
ALTER TABLE documents
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE documents
    ALTER COLUMN id SET DEFAULT nextval('documents_id_seq');

ALTER SEQUENCE documents_id_seq OWNED BY documents.id;

CREATE SEQUENCE IF NOT EXISTS employees_id_seq;
ALTER TABLE employees
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE employees
    ALTER COLUMN id SET DEFAULT nextval('employees_id_seq');

ALTER SEQUENCE employees_id_seq OWNED BY employees.id;

CREATE SEQUENCE IF NOT EXISTS jobs_id_seq;
ALTER TABLE jobs
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE jobs
    ALTER COLUMN id SET DEFAULT nextval('jobs_id_seq');

ALTER SEQUENCE jobs_id_seq OWNED BY jobs.id;

CREATE SEQUENCE IF NOT EXISTS leaves_id_seq;
ALTER TABLE leaves
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE leaves
    ALTER COLUMN id SET DEFAULT nextval('leaves_id_seq');

ALTER SEQUENCE leaves_id_seq OWNED BY leaves.id;

CREATE SEQUENCE IF NOT EXISTS notifications_id_seq;
ALTER TABLE notifications
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE notifications
    ALTER COLUMN id SET DEFAULT nextval('notifications_id_seq');

ALTER SEQUENCE notifications_id_seq OWNED BY notifications.id;

CREATE SEQUENCE IF NOT EXISTS payroll_id_seq;
ALTER TABLE payroll
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE payroll
    ALTER COLUMN id SET DEFAULT nextval('payroll_id_seq');

ALTER SEQUENCE payroll_id_seq OWNED BY payroll.id;

CREATE SEQUENCE IF NOT EXISTS projects_id_seq;
ALTER TABLE projects
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE projects
    ALTER COLUMN id SET DEFAULT nextval('projects_id_seq');

ALTER SEQUENCE projects_id_seq OWNED BY projects.id;

CREATE SEQUENCE IF NOT EXISTS users_id_seq;
ALTER TABLE users
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE users
    ALTER COLUMN id SET DEFAULT nextval('users_id_seq');

ALTER SEQUENCE users_id_seq OWNED BY users.id;

ALTER TABLE users
    ALTER COLUMN is_verified DROP NOT NULL;

ALTER TABLE payroll
ALTER
COLUMN salary_per_month TYPE DECIMAL(12, 2) USING (salary_per_month::DECIMAL(12, 2));